### ISSUE TITLE
Create foaf:lastname foaf:firstname from foaf:name 

### ISSUE THREAD

**Issue by rwarren2** [rwarren2/CanLink#3]
Parse <foaf:name>Boivin, Rémi</foaf:name> to <foaf:firstName> Rémi </foaf:firstName> and <foaf:lastName> Boivin </foaf:lastName> when possible

**Comment by maharshmellow** [comment]
Some of them contain a middle name as well. Should I just put that with the first name or leave the original foaf:name if the middle name is given?

**Comment by rwarren2** [comment]
There is no foaf:middleNames. Concatenate with firstName for now.
