### ISSUE TITLE
Degrees Labelling

### ISSUE THREAD

**Issue by rwarren2** [rwarren2/CanLink#6]
Can you label degree objects with an rdfs:label:

  <rdf:Description rdf:about="http://canlink.library.ualberta.ca/thesisDegree/msc">
    <rdf:type rdf:resource="http://purl.org/ontology/bibo/thesisDegree"/>
  </rdf:Description>

**Comment by maharshmellow** [comment]
So something like this? 
```
<rdf:Description rdf:about="http://canlink.library.ualberta.ca/thesisDegree/msc">
<rdf:type rdf:resource="http://purl.org/ontology/bibo/thesisDegree"/>
<rdfs:label>msc</rdfs:label>
</rdf:Description>

**Comment by rwarren2** [comment]
Yes. Think you can make it Pretty Printed? MSc?
